resources:
- ../../base

namespace: talentcurate-prod

labels:
  - includeSelectors: true
    pairs:
      variant: production

# Base ingress.yaml defaults to app.talentcurate.com and talentcurate.com
