apiVersion: v1
kind: Secret
metadata:
  name: talentcurate-secrets
type: Opaque
stringData:
  GEMINI_API_KEY: "" # INSERT_YOUR_GEMINI_API_KEY_HERE
  LIVEKIT_API_KEY: "devkey"
  LIVEKIT_API_SECRET: "talentcurate_interview_secret_key_32_chars_min"
  ADMIN_PASSWORD: "admin123"
  POSTGRES_PASSWORD: "interviewpass"
  MINIO_ROOT_PASSWORD: "minioadmin"
